use registry for caching

diff --git a/.github/workflows/build-pr.yml b/.github/workflows/build-pr.yml
--- a/.github/workflows/build-pr.yml
+++ b/.github/workflows/build-pr.yml
@@ -14,6 +14,14 @@ on:
 jobs:
   build-document-manager:
     runs-on: ubuntu-20.04
+    services:
+      registry:
+        image: zero88/gh-registry:latest
+        ports:
+          - 5000:5000
+        options: >-
+          -v /home/runner:/var/lib/registry
+          --name registry
     environment: Development
     env:
       BUILD_LOGLEVEL: "2"
@@ -27,15 +35,19 @@ jobs:
         id: buildx
         uses: docker/setup-buildx-action@v1
         with:
-          install: true
+          driver-opts: network=host
         
       - name: Cache Docker layers
         uses: actions/cache@v2
         with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          path: /home/runner/docker
+          key: ${{ runner.os }}-docker-${{ github.sha }}
           restore-keys: |
-            ${{ runner.os }}-buildx-
+            ${{ runner.os }}-docker-
+
+      - name: Validate cache
+        run: |
+          docker buildx imagetools inspect localhost:5000/${{ env.APP_IMAGE }}:buildcache || echo "Not Found"
 
       - name: "Login to OpenShift repository"
         uses: docker/login-action@v1
@@ -68,18 +80,15 @@ jobs:
             BUILD_LOGLEVEL=1
             SVC_NAME=pr-${{steps.PR.outputs.number}}
           tags: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/prime-document-manager:pr-${{steps.PR.outputs.number}}
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache
+          cache-from: type=registry,ref=localhost:5000/test:buildcache
+          cache-to: type=registry,ref=localhost:5000/test:buildcache,mode=max
           push: true
 
-      -
-        # Temp fix
-        # https://github.com/docker/build-push-action/issues/252
-        # https://github.com/moby/buildkit/issues/1896
-        name: Move cache
+      - name: Cleanup Docker build cache if any
         run: |
-          rm -rf /tmp/.buildx-cache
-          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+          docker buildx imagetools inspect localhost:5000/test:buildcache
+          echo "======================================================"
+          docker buildx prune --filter until=72h --keep-storage 5GB -f
 
       # - name: "Build, tag and push Document Manager image"
       #   id: build-image
@@ -99,6 +108,14 @@ jobs:
 
   build-webapi:
     runs-on: ubuntu-20.04
+    services:
+      registry:
+        image: zero88/gh-registry:latest
+        ports:
+          - 5000:5000
+        options: >-
+          -v /home/runner:/var/lib/registry
+          --name registry
     environment: Development
     env:
       SERVICE_NAME: dotnet-webapi
@@ -111,15 +128,19 @@ jobs:
         id: buildx
         uses: docker/setup-buildx-action@v1
         with:
-          install: true
+          driver-opts: network=host
         
       - name: Cache Docker layers
         uses: actions/cache@v2
         with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          path: /home/runner/docker
+          key: ${{ runner.os }}-docker-${{ github.sha }}
           restore-keys: |
-            ${{ runner.os }}-buildx-
+            ${{ runner.os }}-docker-
+
+      - name: Validate cache
+        run: |
+          docker buildx imagetools inspect localhost:5000/${{ env.APP_IMAGE }}:buildcache || echo "Not Found"
 
       - name: "Login to OpenShift repository"
         uses: docker/login-action@v1
@@ -161,18 +182,15 @@ jobs:
             POSTGRESQL_DATABASE=prime-dev
             SVC_NAME=pr-${{steps.PR.outputs.number}}
           tags: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/prime-webapi-backend:pr-${{steps.PR.outputs.number}}
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache
+          cache-from: type=registry,ref=localhost:5000/test:buildcache
+          cache-to: type=registry,ref=localhost:5000/test:buildcache,mode=max
           push: true
 
-      -
-        # Temp fix
-        # https://github.com/docker/build-push-action/issues/252
-        # https://github.com/moby/buildkit/issues/1896
-        name: Move cache
+      - name: Cleanup Docker build cache if any
         run: |
-          rm -rf /tmp/.buildx-cache
-          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+          docker buildx imagetools inspect localhost:5000/test:buildcache
+          echo "======================================================"
+          docker buildx prune --filter until=72h --keep-storage 5GB -f
 
       # - name: "Build, tag and push .NET web API image"
       #   id: build-image
@@ -202,6 +220,14 @@ jobs:
 
   build-frontend:
     runs-on: ubuntu-20.04
+    services:
+      registry:
+        image: zero88/gh-registry:latest
+        ports:
+          - 5000:5000
+        options: >-
+          -v /home/runner:/var/lib/registry
+          --name registry
     environment: Development
     env:
       SERVICE_NAME: nginx-angular
@@ -218,15 +244,19 @@ jobs:
         id: buildx
         uses: docker/setup-buildx-action@v1
         with:
-          install: true
+          driver-opts: network=host
         
       - name: Cache Docker layers
         uses: actions/cache@v2
         with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          path: /home/runner/docker
+          key: ${{ runner.os }}-docker-${{ github.sha }}
           restore-keys: |
-            ${{ runner.os }}-buildx-
+            ${{ runner.os }}-docker-
+
+      - name: Validate cache
+        run: |
+          docker buildx imagetools inspect localhost:5000/${{ env.APP_IMAGE }}:buildcache || echo "Not Found"
 
       - name: "Login to OpenShift repository"
         uses: docker/login-action@v1
@@ -264,18 +294,15 @@ jobs:
             SVC_NAME=pr-${{steps.PR.outputs.number}}
             REDIRECT_URL="https://pr-${{steps.PR.outputs.number}}.pharmanetenrolment.gov.bc.ca"
           tags: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/prime-frontend:pr-${{steps.PR.outputs.number}}
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache
+          cache-from: type=registry,ref=localhost:5000/test:buildcache
+          cache-to: type=registry,ref=localhost:5000/test:buildcache,mode=max
           push: true
 
-      -
-        # Temp fix
-        # https://github.com/docker/build-push-action/issues/252
-        # https://github.com/moby/buildkit/issues/1896
-        name: Move cache
+      - name: Cleanup Docker build cache if any
         run: |
-          rm -rf /tmp/.buildx-cache
-          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+          docker buildx imagetools inspect localhost:5000/test:buildcache
+          echo "======================================================"
+          docker buildx prune --filter until=72h --keep-storage 5GB -f
 
       # - name: "Build, tag & push Angular frontend image"
       #   id: build-image
