specify cache image name

diff --git a/.github/workflows/build-pr.yml b/.github/workflows/build-pr.yml
--- a/.github/workflows/build-pr.yml
+++ b/.github/workflows/build-pr.yml
@@ -47,7 +47,7 @@ jobs:
 
       - name: Validate cache
         run: |
-          docker buildx imagetools inspect localhost:5000/${{ env.APP_IMAGE }}:buildcache || echo "Not Found"
+          docker buildx imagetools inspect localhost:5000/docman:buildcache || echo "Not Found"
 
       - name: "Login to OpenShift repository"
         uses: docker/login-action@v1
@@ -140,7 +140,7 @@ jobs:
 
       - name: Validate cache
         run: |
-          docker buildx imagetools inspect localhost:5000/${{ env.APP_IMAGE }}:buildcache || echo "Not Found"
+          docker buildx imagetools inspect localhost:5000/webapi:buildcache || echo "Not Found"
 
       - name: "Login to OpenShift repository"
         uses: docker/login-action@v1
@@ -256,7 +256,7 @@ jobs:
 
       - name: Validate cache
         run: |
-          docker buildx imagetools inspect localhost:5000/${{ env.APP_IMAGE }}:buildcache || echo "Not Found"
+          docker buildx imagetools inspect localhost:5000/frontend:buildcache || echo "Not Found"
 
       - name: "Login to OpenShift repository"
         uses: docker/login-action@v1
